name: PR update
on:
  pull_request:
    types: [opened]

jobs:
  update_pr:
    name: PR update
    runs-on: ubuntu-latest
    steps:
      - name: Check Branch
        id: check-branch
        run: |
          if [[ ${{ github.head_ref }} =~ [twTW]+-[0-9]+$ ]]; then
              echo ::set-output name=match::true
          fi
      - uses: tzkhan/pr-update-action@v2
        if: steps.check-branch.outputs.match == 'true'
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          base-branch-regex: '[A-Za-z\d-_.\\/]+'
          head-branch-regex: '([twTW])+-\d+'
          title-template: " `%headbranch%`"
          title-update-action: "suffix"
          body-template: |
            Jira issue: [%headbranch%](https://thg.atlassian.net/browse/%headbranch%)
            ---

            # Checklist:

            - [ ] I have performed a self-review of my code
            - [ ] I have commented my code, particularly in hard-to-understand areas
            - [ ] I have created a QA task if necessary in Jira


            # Summary
            
            
          body-update-action: "prefix"
          body-uppercase-base-match: false
