name: Lint frontend code
on:
  pull_request:
    types: [opened, synchronize]
    branches:
     - 'feature/**'
    paths:
     - '**/app/**'

jobs:
  lint_frontend_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request')
    name: Lint frontend code
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v3
        with:
          submodules: false

      - name: Install Node.js
        uses: actions/setup-node@v3.3.0
        with:
          node-version: 14
          check-latest: true
          registry-url: "https://npm.pkg.github.com"

      - name: Authenticate with private NPM package
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.AUTH }}" > ~/.npmrc

      - run: npm install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.AUTH }}
        working-directory: 'app'
      - run: npm run lint
        working-directory: 'app'
